const cloud = require('wx-server-sdk');

cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });

exports.main = async () => {
  return {
    success: true,
    profile: {
      name: 'Farland Guest',
      member_level: 'Farland Signature',
      points_balance: 3280,
    },
    today_itinerary: {
      date: '2026-06-03',
      city: 'Boston',
      title: 'Boston Campus Visit Day',
      summary: '全天访校行程，Farland 顾问已协调酒店出发、校园停靠、午间节奏与用车安排。',
      items: [
        {
          time: '09:00',
          type: 'departure',
          title: '酒店出发',
          description: 'Boston Marriott Cambridge 大堂集合，司机将提前抵达等候。',
        },
        {
          time: '10:00',
          type: 'campus',
          title: 'Harvard University',
          description: '校园参访与周边生活环境了解。',
        },
        {
          time: '13:00',
          type: 'campus',
          title: 'MIT Campus Visit',
          description: 'MIT 主校区参访，午餐时间根据现场节奏调整。',
        },
        {
          time: '14:30',
          type: 'transfer_request',
          title: '接送需求已提交',
          description: 'Boston College → 酒店，Farland 正在确认返程用车方案。',
          linked_entity_type: 'transfer_request',
          linked_entity_id: 'tr_boston_return_001',
          client_status: 'quoted',
        },
        {
          time: '16:00',
          type: 'campus',
          title: 'Boston College',
          description: '下午访校结束后返回酒店，晚餐可由顾问协助建议。',
        },
      ],
      driver: {
        name: 'David',
        phone: '+1 (617) 000-0000',
        vehicle: 'Chevrolet Suburban',
      },
      farland_contact: {
        name: 'Farland Advisor',
        phone: '+1 (800) 000-0000',
      },
    },
    trip_overview: [
      {
        day: 1,
        date: '2026-06-03',
        city: 'Boston',
        title: 'Boston Campus Visit',
        status: 'confirmed',
        summary: 'Harvard / MIT / Boston College 访校与 Cambridge 周边住宿。',
      },
      {
        day: 2,
        date: '2026-06-04',
        city: 'New York',
        title: 'New York Transfer',
        status: 'pending',
        summary: '跨城转场与酒店入住，顾问协助确认出发时间和行李安排。',
      },
    ],
    transportation_appointments: [
      {
        service_date: '2026-06-03',
        service_type: '访校包车',
        route_summary: 'Boston campus visit: Harvard / MIT / Boston College',
        status: 'assigned',
        driver_name: 'David',
        driver_phone: '+1 (617) 000-0000',
        vehicle_type: 'Suburban',
        vehicle_model: 'Chevrolet Suburban',
        plate_number: 'Confirmed',
      },
    ],
    charter_services: [
      {
        charter_id: 'charter_boston_001',
        title: '访校包车服务',
        date_range_text: '2026-06-03｜每日 10 小时',
        vehicle_class: 'Large SUV',
        service_area: 'Boston / Cambridge 校园路线',
        continuity_text: '优先同一司机；如因工时或档期需要调整，Farland 将协调同等级替补。',
        status: 'confirmed',
        status_text: '已确认',
        segments: [
          {
            time: '09:00',
            title: '酒店出发',
            route: 'Boston Marriott Cambridge → Harvard University',
          },
          {
            time: '13:00',
            title: '校际转场',
            route: 'Harvard / MIT 周边 → Boston College',
          },
        ],
      },
    ],
    transfer_requests: [
      {
        request_id: 'tr_boston_return_001',
        title: 'Boston College 返程接送',
        created_by_text: '由 Farland 顾问代您提交',
        pickup: 'Boston College',
        dropoff: 'Boston Marriott Cambridge',
        pickup_time_text: '2026-06-03 17:30',
        passengers: 3,
        luggage: 3,
        flight_no: '',
        special_needs: ['中文沟通优先', '行李较多'],
        status: 'quoted',
        status_text: '已收到优选用车方案',
        ops_status_text: 'Farland 已为您筛选以下优选用车方案。',
        quotes: [
          {
            quote_id: 'qt_boston_001',
            public_title: 'Farland 推荐｜商务 SUV 返程方案',
            suitable_for: '适合家长同行 / 行李较多 / 校园返程',
            vehicle_class: 'Business SUV',
            capacity_text: '3-4 人 / 4 件行李',
            driver_profile_teaser: '中文沟通｜稳重细致｜熟悉 Boston 学校路线',
            includes: ['校门接送', '基础等待 30 分钟', '行李协助'],
            excludes: ['临时加点', '超时等待'],
            valid_until_text: '报价保留至今天 15:00',
            driver_quote_amount: 220,
            farland_service_fee_rate: 0.1,
            farland_service_fee_amount: 22,
            client_visible_total: 242,
            currency: 'USD',
            is_recommended: true,
            status: 'published',
          },
          {
            quote_id: 'qt_boston_002',
            public_title: '高性价比｜7 座 MPV 方案',
            suitable_for: '适合预算敏感 / 轻行李 / 标准返程',
            vehicle_class: '7-seat MPV',
            capacity_text: '2-4 人 / 3 件行李',
            driver_profile_teaser: '中文沟通｜服务稳定｜熟悉酒店接送',
            includes: ['校门接送', '基础等待 30 分钟'],
            excludes: ['停车费', '超时等待'],
            valid_until_text: '报价保留至今天 15:00',
            driver_quote_amount: 180,
            farland_service_fee_rate: 0.1,
            farland_service_fee_amount: 18,
            client_visible_total: 198,
            currency: 'USD',
            is_recommended: false,
            status: 'published',
          },
          {
            quote_id: 'qt_boston_003',
            public_title: '大空间｜Suburban 方案',
            suitable_for: '适合多人 / 大件行李 / 舒适优先',
            vehicle_class: 'Large SUV',
            capacity_text: '4-6 人 / 5 件行李',
            driver_profile_teaser: '中英双语｜商务专业｜适合家庭访校',
            includes: ['校门接送', '基础等待 45 分钟', '行李协助'],
            excludes: ['临时绕路', '停车费'],
            valid_until_text: '报价保留至今天 15:00',
            driver_quote_amount: 280,
            farland_service_fee_rate: 0.1,
            farland_service_fee_amount: 28,
            client_visible_total: 308,
            currency: 'USD',
            is_recommended: false,
            status: 'published',
          },
        ],
        activity_events: [
          {
            time: '10:42',
            message: '接送需求已提交',
          },
          {
            time: '10:55',
            message: 'Farland 开始确认优选用车方案',
          },
          {
            time: '11:18',
            message: '已发布 3 个优选用车方案',
          },
        ],
      },
    ],
    transport_orders: [
      {
        order_id: 'to_airport_001',
        title: '机场接送已预约',
        pickup: 'Logan Airport Terminal E',
        dropoff: 'Boston Marriott Cambridge',
        pickup_time_text: '2026-06-03 08:15',
        vehicle_class: 'Business SUV',
        order_status: 'assigned',
        status_text: '已分配司机',
        selected_quote_total: 242,
        currency: 'USD',
        driver: {
          display_name: 'Driver D.',
          phone: '+1 (617) 000-0000',
          vehicle_model: 'Chevrolet Suburban',
          plate_number: 'Confirmed',
          meeting_point: 'Terminal E Arrivals',
        },
      },
    ],
    hotel_requests: [
      {
        city: 'Boston',
        hotel_name: '',
        room_type: '',
        check_in_date: '2026-06-03',
        check_out_date: '2026-06-06',
        status: 'processing',
      },
    ],
    benefits: [
      {
        title: '机场接送礼遇',
        description: '指定城市机场接送服务可享 Farland 会员权益',
      },
      {
        title: '酒店预订礼遇',
        description: '顾问协助筛选校园周边与高端品牌酒店方案',
      },
      {
        title: '访校行程咨询',
        description: '美国学校参访动线、住宿区域与用车节奏建议',
      },
    ],
  };
};
